tienda_ceramica/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from products import views as product_views
from cart import views as cart_views

urlpatterns = [
    path("", product_views.HomepageView.as_view(), name="homepage"),
    path("<int:pk>", product_views.DetailView.as_view(), name="detail"),
    path("carrito", cart_views.LocalStorageCartView.as_view(), name="carritolocal"),
    path("add/<int:pieza_id>/", cart_views.AddToCart.as_view(), name="AddToCart"),
    path(
        "remove/<int:pieza_id>/",
        cart_views.RemoveFromCart.as_view(),
        name="RemoveFromCart",
    ),
    path(
        "micarrito",
        cart_views.DatabaseCartView.as_view(),
        name="micarrito",
    ),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("cuenta/", include("users.urls")),
    path("api/stock/<int:product_id>", product_views.stock_view, name="stock_view"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("edit-profile/", views.edit_profile, name="edit_profile"),
]

templates/cuenta/edit-profile.html
{% extends 'base.html' %} 
{% block title %} Editar información de perfil 
{% load tailwind_filters static %}
{% endblock %} 
{% block content %}

<form method="post" action="{% url 'users:edit_profile' %}">
  {% csrf_token %} {{ form|crispy}}
  <button type="submit">Enviar</button>
</form>
{% endblock %}

templates/cuenta/logged_out.html
{% extends 'base.html' %} {% block content %}
<p>¡Sesión finalizada!</p>

<a href="{% url 'login'%}">Haga clic aquí para iniciar sesión nuevamente.</a>
{% endblock %}

templates/cuenta/login.html
{% extends 'base.html' %}
{% load tailwind_filters static %}
{% block content %}

  {% if form.errors %}
    <p>Su nombre de usuario y contraseña no coinciden. Inténtalo de nuevo.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>Su cuenta no tiene acceso a esta página. Para continuar,
      inicie sesión con una cuenta que tenga acceso.</p>
    {% else %}
      <p>Por favor inicie sesión para ver esta página.</p>
    {% endif %}
  {% endif %}

<div class="relative bg-cover bg-center " style="background-image: url('{% static 'img/fondo9.jpg' %}'); background-attachment: fixed;">
    <div class="relative z-10 py-36 flex items-center justify-center h-full">
        <div class="bg-white p-8 rounded-lg shadow-lg max-w-lg md:max-w-2xl w-full mx-4">

  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
                <div class="mb-4">{{ form|crispy }}</div>
                <button type="submit" class="w-full py-3 mt-4 bg-yellow-800 text-white font-semibold rounded-md hover:bg-yellow-700 focus:outline-none focus:ring-2 focus:ring-yellow-300">
                    Iniciar sesión
                </button>
  </form>

    <section class="py-2">
      <h5>¿No tienes cuenta en Cerámica Artesanal?</h5>
      <a href="{% url 'users:register' %}?next={{ request.GET.next | default:request.path }}" class="font-semibold">Registrate</a>

    </section>
    </div>
    </div>
    </div>

{% endblock %}

templates/cuenta/password_reset_complete.html
{% extends "base_generic.html" %}
{% block content %}

<h1>¡La contraseña ha sido cambiada!</h1>
<p><a href="{% url 'login' %}">¿ingresar de nuevo?</a></p>

{% endblock %}

templates/cuenta/password_reset_confirm.html
{% extends "base.html" %} {% block content %} {% if validlink %}
<p>Ingrese (y confirme) su nueva contraseña.</p>
<form action="" method="post">
  <div style="display: none">
    <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken" />
  </div>
  <table>
    <tr>
      <td>
        {{ form.new_password1.errors }}
        <label for="id_new_password1">Nueva contraseña:</label>
      </td>
      <td>{{ form.new_password1 }}</td>
    </tr>
    <tr>
      <td>
        {{ form.new_password2.errors }}
        <label for="id_new_password2">Confirmar contraseña:</label>
      </td>
      <td>{{ form.new_password2 }}</td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" value="Cambiar mi contraseña" /></td>
    </tr>
  </table>
</form>
{% else %}
<h1>Error al restablecer la contraseña</h1>
<p>
  El enlace para restablecer la contraseña no era válido, posiblemente porque ya
  se había utilizado. Solicite un nuevo restablecimiento de contraseña.
</p>
{% endif %} {% endblock %}

templates/cuenta/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<p>Le hemos enviado por correo electrónico instrucciones para configurar su contraseña. Si no han llegado en unos minutos, revisa tu carpeta de spam.</p>
{% endblock %}

templates/cuenta/password_reset_email.html
Alguien solicitó restablecer la contraseña del correo electrónico {{ email }}. Vaya el siguiente enlace:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

templates/cuenta/password_reset_form.html
{% extends "base.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %} {% if form.email.errors %} {{ form.email.errors }} {% endif
  %}
  <p>{{ form.email }}</p>
  <input
    type="submit"
    class="btn btn-default btn-lg"
    value="Restablecer contraseña"
  />
</form>
{% endblock %}

templates/cuenta/registro.html
{% extends 'base.html' %}
{% load tailwind_filters static %}
{% block title %} Registrarse en Cerámica artesanal {% endblock %}
{% block extra_head %}
<script type="module" defer src="{% static 'js/cart/registration-cart-to-database.js'  %}"></script>
{% endblock %} 
{% block content %}
            <h2 class="text-center text-2xl font-semibold mb-6">Registrate en Cerámica artesanal</h2>
<!-- WARN: La imagen es muy pesada -->
<div class="relative bg-cover bg-center " style="background-image: url('{% static 'img/fondo9.jpg' %}'); background-attachment: fixed;">
    <div class="relative z-10 py-4 flex items-center justify-center h-full">
        <div class="bg-white p-8 rounded-lg shadow-lg max-w-lg md:max-w-2xl w-full mx-4">

            <form class="focus:outline-none focus:ring-2 focus:ring-yellow-300" method="POST" novalidate>
                {% csrf_token %}
                <div class="mb-4">{{ form|crispy }}</div>
        <input type="checkbox" id="conservar-carrito" name="conservar_carrito">
        <label for="conservar-carrito">¿Quiere conservar el carrito de la compra actual?</label>
    <input type="hidden" id="carrito-data" name="carrito_data">

                <!-- Botón de registrarse -->
                <button type="submit" class="w-full py-3 mt-4 bg-yellow-800 text-white font-semibold rounded-md hover:bg-yellow-700 focus:outline-none focus:ring-2 focus:ring-yellow-300">
                    Registrarse
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}